import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { config } from "dotenv";
import fs from "node:fs";
import path from "node:path";

const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));

config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
let outdir = "smart-fold";
if (!prod) {
  const vaultDir =
    process.env.REAL === "1" ? process.env.REAL_VAULT : process.env.TEST_VAULT;
  if (vaultDir) {
    outdir = path.join(vaultDir, ".obsidian", "plugins", manifest.id);
  }
}

console.info(`\nSaving plugin to ${outdir}\n`);

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  minify: prod ? true : false,
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "codemirror",
    "@codemirror/autocomplete",
    "@codemirror/closebrackets",
    "@codemirror/commands",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: outdir,
});

if (prod) {
  await context.rebuild();
  fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
  process.exit(0);
} else {
  await context.watch();
  fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
}
