import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));

// Optional .env with TEST_VAULT / REAL_VAULT for dev builds, read with
// Node's built-in loader instead of the dotenv package.
try {
  process.loadEnvFile();
} catch {
  // no .env file
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
// Production builds go to the repository root, where Obsidian's community
// directory looks for main.js when it verifies a release against the source.
let outdir = ".";
if (!prod) {
  const vaultDir =
    process.env.REAL === "1" ? process.env.REAL_VAULT : process.env.TEST_VAULT;
  if (vaultDir) {
    outdir = path.join(vaultDir, ".obsidian", "plugins", manifest.id);
  }
}

console.info(`\nSaving plugin to ${outdir}\n`);

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  minify: prod ? true : false,
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "codemirror",
    "@codemirror/autocomplete",
    "@codemirror/closebrackets",
    "@codemirror/commands",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: outdir,
});

const copyManifest = () => {
  if (path.resolve(outdir) !== path.resolve(".")) {
    fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
  }
};

if (prod) {
  await context.rebuild();
  copyManifest();
  process.exit(0);
} else {
  await context.watch();
  copyManifest();
}
